"""
Forensic Assessment Report PDF Generator using ReportLab.
Produces enterprise-grade DFIR audit reports with executive summaries, risk matrices, and remediation playbooks.
"""

import os
from typing import List, Dict, Any
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.units import inch
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak, KeepTogether, HRFlowable
)
from reportlab.pdfgen import canvas
from core.models import ForensicAssessmentReport, StartupEntry, ThreatSeverity
from core.analyzer.mitre_mapper import MITREMapper


class NumberedCanvas(canvas.Canvas):
    """Adds professional running headers and footers with dynamic page numbering."""
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super().showPage()
        super().save()

    def draw_page_decorations(self, page_count: int):
        self.saveState()
        self.setFont("Helvetica", 8)
        self.setFillColor(colors.HexColor("#718096"))

        # Header (pages > 1)
        if self._pageNumber > 1:
            self.drawString(54, 750, "Windows Startup Program & Persistence Forensic Assessment")
            self.drawRightString(558, 750, "CONFIDENTIAL / DFIR REPORT")
            self.setStrokeColor(colors.HexColor("#CBD5E0"))
            self.setLineWidth(0.5)
            self.line(54, 742, 558, 742)

        # Footer
        self.setStrokeColor(colors.HexColor("#CBD5E0"))
        self.setLineWidth(0.5)
        self.line(54, 45, 558, 45)
        self.drawString(54, 32, "Generated by WinASEP Forensic Inspector | Digital Forensics & Incident Response")
        page_str = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(558, 32, page_str)
        self.restoreState()


class PDFReportGenerator:
    """Generates comprehensive PDF forensic assessment reports."""

    @classmethod
    def generate(cls, report: ForensicAssessmentReport, output_path: str) -> str:
        """Generates PDF report and saves to output_path."""
        os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)
        
        doc = SimpleDocTemplate(
            output_path,
            pagesize=letter,
            leftMargin=54,
            rightMargin=54,
            topMargin=54,
            bottomMargin=54
        )

        styles = getSampleStyleSheet()
        
        # Custom Typography Styles
        title_style = ParagraphStyle(
            'DocTitle',
            parent=styles['Normal'],
            fontName='Helvetica-Bold',
            fontSize=22,
            leading=26,
            textColor=colors.HexColor("#0F172A"),
            spaceAfter=6
        )
        subtitle_style = ParagraphStyle(
            'DocSubtitle',
            parent=styles['Normal'],
            fontName='Helvetica',
            fontSize=11,
            leading=14,
            textColor=colors.HexColor("#475569"),
            spaceAfter=15
        )
        h1_style = ParagraphStyle(
            'Heading1_Custom',
            parent=styles['Heading1'],
            fontName='Helvetica-Bold',
            fontSize=14,
            leading=18,
            textColor=colors.HexColor("#0F172A"),
            spaceBefore=14,
            spaceAfter=8,
            keepWithNext=True
        )
        h2_style = ParagraphStyle(
            'Heading2_Custom',
            parent=styles['Heading2'],
            fontName='Helvetica-Bold',
            fontSize=11,
            leading=14,
            textColor=colors.HexColor("#1E293B"),
            spaceBefore=10,
            spaceAfter=4,
            keepWithNext=True
        )
        body_style = ParagraphStyle(
            'Body_Custom',
            parent=styles['BodyText'],
            fontName='Helvetica',
            fontSize=9,
            leading=12,
            textColor=colors.HexColor("#334155")
        )
        body_bold = ParagraphStyle(
            'Body_Bold',
            parent=body_style,
            fontName='Helvetica-Bold'
        )
        code_style = ParagraphStyle(
            'Code_Custom',
            parent=styles['Normal'],
            fontName='Courier',
            fontSize=7.5,
            leading=10,
            textColor=colors.HexColor("#0F172A")
        )

        story = []

        # --- COVER / HEADER BANNER ---
        story.append(Paragraph("FORENSIC ASSESSMENT REPORT", title_style))
        story.append(Paragraph("Windows Auto-Start Extensibility Points (ASEP) & Persistence Threat Analysis", subtitle_style))
        story.append(HRFlowable(width="100%", thickness=1.5, color=colors.HexColor("#0284C7"), spaceAfter=12))

        # --- METADATA & EXECUTIVE SUMMARY TABLE ---
        meta_data = [
            [
                Paragraph("<b>Report ID:</b>", body_style), Paragraph(report.report_id, body_style),
                Paragraph("<b>Scan Timestamp:</b>", body_style), Paragraph(report.scan_timestamp, body_style)
            ],
            [
                Paragraph("<b>Target Host:</b>", body_style), Paragraph(report.host_name or "Local Machine", body_style),
                Paragraph("<b>Operating System:</b>", body_style), Paragraph(report.os_version or "Windows", body_style)
            ],
            [
                Paragraph("<b>Total ASEPs Analyzed:</b>", body_style), Paragraph(str(report.total_analyzed), body_bold),
                Paragraph("<b>Scan Duration:</b>", body_style), Paragraph(f"{report.duration_seconds:.2f}s", body_style)
            ],
            [
                Paragraph("<b>System Risk Score:</b>", body_style), Paragraph(f"<b>{report.overall_risk_score}/100 ({report.overall_risk_level})</b>", body_bold),
                Paragraph("<b>Target User:</b>", body_style), Paragraph(report.target_user or "Current User", body_style)
            ]
        ]
        meta_table = Table(meta_data, colWidths=[110, 140, 110, 144])
        meta_table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,-1), colors.HexColor("#F8FAFC")),
            ('BOX', (0,0), (-1,-1), 1, colors.HexColor("#E2E8F0")),
            ('INNERGRID', (0,0), (-1,-1), 0.5, colors.HexColor("#E2E8F0")),
            ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
            ('TOPPADDING', (0,0), (-1,-1), 4),
            ('BOTTOMPADDING', (0,0), (-1,-1), 4),
        ]))
        story.append(meta_table)
        story.append(Spacer(1, 14))

        # --- THREAT LEVEL METRIC CARDS ---
        crit_color = colors.HexColor("#EF4444")
        high_color = colors.HexColor("#F97316")
        med_color = colors.HexColor("#F59E0B")
        low_color = colors.HexColor("#3B82F6")
        clean_color = colors.HexColor("#10B981")

        metric_data = [
            [
                Paragraph("<font color='#EF4444' size=14><b>CRITICAL</b></font><br/><font size=16><b>" + str(report.critical_count) + "</b></font>", ParagraphStyle('C1', alignment=1)),
                Paragraph("<font color='#F97316' size=14><b>HIGH</b></font><br/><font size=16><b>" + str(report.high_count) + "</b></font>", ParagraphStyle('C2', alignment=1)),
                Paragraph("<font color='#F59E0B' size=14><b>MEDIUM</b></font><br/><font size=16><b>" + str(report.medium_count) + "</b></font>", ParagraphStyle('C3', alignment=1)),
                Paragraph("<font color='#3B82F6' size=14><b>LOW</b></font><br/><font size=16><b>" + str(report.low_count) + "</b></font>", ParagraphStyle('C4', alignment=1)),
                Paragraph("<font color='#10B981' size=14><b>CLEAN</b></font><br/><font size=16><b>" + str(report.clean_count) + "</b></font>", ParagraphStyle('C5', alignment=1)),
            ]
        ]
        metric_table = Table(metric_data, colWidths=[100, 100, 100, 100, 104])
        metric_table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (0,0), colors.HexColor("#FEF2F2")),
            ('BACKGROUND', (1,0), (1,0), colors.HexColor("#FFF7ED")),
            ('BACKGROUND', (2,0), (2,0), colors.HexColor("#FEFCE8")),
            ('BACKGROUND', (3,0), (3,0), colors.HexColor("#EFF6FF")),
            ('BACKGROUND', (4,0), (4,0), colors.HexColor("#ECFDF5")),
            ('BOX', (0,0), (-1,-1), 1, colors.HexColor("#CBD5E1")),
            ('INNERGRID', (0,0), (-1,-1), 1, colors.HexColor("#CBD5E1")),
            ('ALIGN', (0,0), (-1,-1), 'CENTER'),
            ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
            ('TOPPADDING', (0,0), (-1,-1), 6),
            ('BOTTOMPADDING', (0,0), (-1,-1), 6),
        ]))
        story.append(metric_table)
        story.append(Spacer(1, 14))

        # --- SECTION 1: EXECUTIVE SUMMARY & THREAT OVERVIEW ---
        story.append(Paragraph("1. Executive Summary & Forensic Assessment", h1_style))
        summary_text = (
            f"An in-depth automated digital forensic inspection of Windows Auto-Start Extensibility Points (ASEP) "
            f"was executed on <b>{report.host_name or 'the host system'}</b>. A total of <b>{report.total_analyzed} startup mechanisms</b> "
            f"were inspected across Registry Run keys, Winlogon, Image File Execution Options (IFEO), Active Setup, "
            f"Startup Folders, Scheduled Tasks, Windows Services, WMI Event Subscriptions, and System Drivers. "
            f"<br/><br/>The system received an overall Suspicion Risk Score of <b>{report.overall_risk_score}/100 ({report.overall_risk_level})</b>. "
        )
        if report.critical_count > 0 or report.high_count > 0:
            summary_text += (
                f"<font color='#DC2626'><b>CRITICAL ATTENTION REQUIRED:</b></font> A total of <b>{report.critical_count} Critical</b> and "
                f"<b>{report.high_count} High-risk</b> persistent anomalies were identified that warrant immediate containment and remediation."
            )
        else:
            summary_text += "No critical or high-risk active persistence anomalies were detected during the examination period."

        story.append(Paragraph(summary_text, body_style))
        story.append(Spacer(1, 14))

        # --- SECTION 2: HIGH RISK FINDINGS DEEP-DIVE ---
        if report.high_risk_entries:
            story.append(Paragraph("2. Critical & High-Risk Persistence Findings", h1_style))
            story.append(Paragraph("The following items triggered high-confidence heuristic rule violations or MITRE ATT&CK indicators:", body_style))
            story.append(Spacer(1, 8))

            for idx, entry in enumerate(report.high_risk_entries, 1):
                card_elements = []
                sev_color = "#DC2626" if entry.severity == ThreatSeverity.CRITICAL else "#EA580C"
                
                # Finding Header
                header_text = f"<b>Finding #{idx}: {entry.name}</b> &nbsp;&nbsp;|&nbsp;&nbsp; <font color='{sev_color}'><b>[{entry.severity.value} - Score: {entry.total_score}/100]</b></font>"
                card_elements.append(Paragraph(header_text, h2_style))
                
                # Detail table
                detail_rows = [
                    [Paragraph("<b>Category:</b>", body_style), Paragraph(entry.category.value, body_style)],
                    [Paragraph("<b>Location:</b>", body_style), Paragraph(entry.location, code_style)],
                    [Paragraph("<b>Command / Target:</b>", body_style), Paragraph(entry.raw_command, code_style)],
                    [Paragraph("<b>Resolved Binary:</b>", body_style), Paragraph(entry.resolved_path or "N/A", code_style)],
                ]

                if entry.signature:
                    sig_str = f"Status: <b>{entry.signature.status}</b>"
                    if entry.signature.signer_name:
                        sig_str += f" | Signer: {entry.signature.signer_name}"
                    detail_rows.append([Paragraph("<b>Digital Signature:</b>", body_style), Paragraph(sig_str, body_style)])

                if entry.file_info and entry.file_info.exists:
                    hash_str = f"SHA256: {entry.file_info.sha256}<br/>Entropy: <b>{entry.file_info.entropy}/8.0</b>"
                    if entry.file_info.is_high_entropy:
                        hash_str += " <font color='#DC2626'><b>(HIGH ENTROPY / PACKED)</b></font>"
                    detail_rows.append([Paragraph("<b>Cryptographic Hash & PE:</b>", body_style), Paragraph(hash_str, code_style)])

                if entry.findings:
                    findings_html = "<ul style='margin-left: 10px;'>"
                    for f in entry.findings:
                        findings_html += f"<li><b>[{f.severity.value}] {f.rule_name}:</b> {f.description}</li>"
                    findings_html += "</ul>"
                    detail_rows.append([Paragraph("<b>Triggered Rules:</b>", body_style), Paragraph(findings_html, body_style)])

                if entry.remediation_command:
                    rem_html = f"<code>{entry.remediation_command}</code>"
                    detail_rows.append([Paragraph("<b>Remediation:</b>", body_style), Paragraph(rem_html, code_style)])

                detail_table = Table(detail_rows, colWidths=[120, 384])
                detail_table.setStyle(TableStyle([
                    ('BACKGROUND', (0,0), (-1,-1), colors.HexColor("#F8FAFC")),
                    ('BOX', (0,0), (-1,-1), 1, colors.HexColor("#E2E8F0")),
                    ('INNERGRID', (0,0), (-1,-1), 0.5, colors.HexColor("#E2E8F0")),
                    ('VALIGN', (0,0), (-1,-1), 'TOP'),
                    ('TOPPADDING', (0,0), (-1,-1), 3),
                    ('BOTTOMPADDING', (0,0), (-1,-1), 3),
                ]))
                card_elements.append(detail_table)
                card_elements.append(Spacer(1, 10))

                story.append(KeepTogether(card_elements))
        else:
            story.append(Paragraph("2. Critical & High-Risk Persistence Findings", h1_style))
            story.append(Paragraph("No critical or high-risk entries were detected.", body_style))

        story.append(Spacer(1, 10))

        # --- SECTION 3: MITRE ATT&CK PERSISTENCE HEATMAP ---
        story.append(Paragraph("3. MITRE ATT&CK Framework Mapping", h1_style))
        mitre_rows = [
            [
                Paragraph("<b>Technique ID</b>", body_bold),
                Paragraph("<b>Technique Name</b>", body_bold),
                Paragraph("<b>Tactics</b>", body_bold),
                Paragraph("<b>Observed Count</b>", body_bold)
            ]
        ]
        for tech_id, entries_list in report.mitre_summary.items():
            tech_info = MITREMapper.get_details(tech_id)
            mitre_rows.append([
                Paragraph(f"<b>{tech_id}</b>", code_style),
                Paragraph(tech_info.get("name", tech_id), body_style),
                Paragraph(", ".join(tech_info.get("tactics", [])), body_style),
                Paragraph(str(len(entries_list)), body_bold)
            ])

        if len(mitre_rows) > 1:
            mitre_table = Table(mitre_rows, colWidths=[80, 180, 164, 80])
            mitre_table.setStyle(TableStyle([
                ('BACKGROUND', (0,0), (-1,0), colors.HexColor("#F1F5F9")),
                ('BOX', (0,0), (-1,-1), 1, colors.HexColor("#CBD5E1")),
                ('INNERGRID', (0,0), (-1,-1), 0.5, colors.HexColor("#E2E8F0")),
                ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
                ('TOPPADDING', (0,0), (-1,-1), 4),
                ('BOTTOMPADDING', (0,0), (-1,-1), 4),
            ]))
            story.append(mitre_table)
        else:
            story.append(Paragraph("No MITRE ATT&CK persistence techniques were triggered.", body_style))

        story.append(Spacer(1, 14))

        # --- SECTION 4: ACTIONABLE INCIDENT RESPONSE PLAYBOOK ---
        story.append(Paragraph("4. Recommended Remediation Action Plan", h1_style))
        if report.remediation_playbook:
            for idx, action in enumerate(report.remediation_playbook, 1):
                p_text = f"<b>Step {idx}: {action.get('title', 'Remediation Step')}</b><br/>{action.get('description', '')}"
                story.append(Paragraph(p_text, body_style))
                if action.get('command'):
                    story.append(Paragraph(f"<code>{action.get('command')}</code>", code_style))
                story.append(Spacer(1, 4))
        else:
            story.append(Paragraph("Maintain standard baseline monitoring and enforce regular code signing audits.", body_style))

        # Build document with custom canvas
        doc.build(story, canvasmaker=NumberedCanvas)
        return output_path
